version: '3'
services:
  app:
    container_name: frontend
    restart: on-failure:5
    build:
      context: ./
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
      - quirrel
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    environment:
      - NODE_ENV=production
      - WAIT_HOSTS=mysql:3306, redis:6379, quirrel:9181
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
  mysql:
    container_name: mysql
    restart: on-failure:5
    image: "mysql:8-oracle"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    container_name: redis
    restart: on-failure:5
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  quirrel:
    container_name: quirrel
    restart: on-failure:5
    image: "ghcr.io/quirrel-dev/quirrel:sha-8750d2b"
    ports:
      - "9181:9181"
    environment:
      REDIS_URL: "redis://redis:6379"
      PASSPHRASES:
      LOG_LEVEL: error
volumes:
  nodemodules: {}
