import { useCallback, useState } from 'react';
import Head from 'next/head'
import axios from 'axios';

import styles from '../styles/Home.module.scss'
import PodcastComponent, { Podcast } from '@/components/Podcast';

export default function Home() {
  const [searching, setSearching] = useState(false);
  const [results, setResults] = useState<Podcast[]>([]);
  const [query, setQuery] = useState('');

  const search = useCallback(async (e) => {
    e.preventDefault();
    const resp = await axios.post('/api/search-podcasts', {
      search: query,
    });

    console.log(resp.data);

    setResults(resp.data.results || [])
  }, [query]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={search}>
          <input
            type="text"
            placeholder="Search For Podcast"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          <button type="submit">Search</button>
        </form>
        <div>
          {results.map((result: Podcast) => (
            <PodcastComponent
              key={result.collectionId}
              podcast={result}
            />
          ))}
        </div>
      </main>
    </div>
  )
}
